- name: PLAY-01
  hosts: web
  tasks:
  - name: TASK01 PLAY01
    ansible.builtin.debug:
      msg: "This is from PLAY01 and TASK01"
  
- name: PLAY-02
  hosts: web
  tasks:
  - name: TASK01 PLAY02
    ansible.builtin.debug:
      msg: "This is from PLAY02 and TASK01"