- name: install nginx and run
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    package:
      name: nginx
      state: present
  - name: start nginx
    service:
      state: started
      enable: yes
