- name: varibles
  hosts: localhost
  vars:
    COURSE: "DevOps"
    DURATION: "120 hours"
    PLATFORM: "Zoom"
  tasks:
  - name: printing a message
    debug:
      msg: "Hi It is {{COURSE}} 81 batch, Duration is {{DURATION}}, platform is {{PLATFORM}}"