- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: printing course information
    debug:
      msg: "Hi, Course is {{COURSE}} and duration is {{DURATION}}, platform is {{PLATFORM}}"