- name: varibales from prompt
  hosts: localhost
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: DURATION
    prompt: please enter the duration of course
    private: false
  - name: PLATFORM
    prompt: please enter the platofrm of the course training
    private: false
  tasks:
  - name: printing course information
    debug:
      msg: "Hi, this course is {{COURSE}}, duration is {{DURATION}} and platform is {{PLATFORM}}"